"""Shared record and paper-result validation schemas."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Mapping


@dataclass(frozen=True)
class PaperExpectedCounts:
    """Published counts used only to validate a completed pipeline run.

    These constants are not generated by the dry-run planner and must not be
    interpreted as newly computed results.
    """

    registered_trials: int = 563_077
    result_trials: int = 73_427
    mapped_outcome_records: int = 480_273
    normalized_outcome_concepts: int = 237_820
    outcome_categories: int = 21
    unique_condition_strings: int = 26_682
    snomed_condition_concepts: int = 238
    disease_areas: int = 24

    def validate(self, observed: Mapping[str, int]) -> list[str]:
        expected = asdict(self)
        return [
            f"{key}: expected {value:,}, observed {observed.get(key)!r}"
            for key, value in expected.items()
            if observed.get(key) != value
        ]


@dataclass(frozen=True)
class OutcomeRecord:
    nct_id: str
    outcome_id: str
    outcome_title: str
    outcome_type: str | None = None
    phase: str | None = None
    start_date: str | None = None


@dataclass(frozen=True)
class StructuredOutcome:
    object: str
    measure: str | None
    time_frame: str | None

